import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
   subsets: ['latin'],
   display: 'swap', // Prevents invisible text during loading
   weight: ['200', '400', '500', '700'],
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" className={poppins.className}>
         <body>{children}</body>
      </html>
   );
}
